### ISSUE TITLE
Can't get an item into the inventory with ox

### ISSUE THREAD

**Issue by Sina30** [WaypointRP/wp-printer#2] opened 2023-12-17 08:55 UTC
For us it opens but we can't get an item into the inventory with ox with esx 1.10.2

**Comment by BackSH00TER** [comment] 2023-12-30 06:18
@Sina30  See if v1.0.1 fixes the issue for you.

**Comment by Sina30** [comment] 2023-12-30 17:40
[    976906] [b2944_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @wp-placeables/client/placeables.lua:118: attempt to call a nil value (global 'CreateLog')^7
[    976906] [b2944_GTAProce]             MainThrd/ ^3> callback^7 (^5@wp-placeables/client/placeables.lua^7:118)
[    976906] [b2944_GTAProce]             MainThrd/ ^3> Progressbar^7 (^5@wp-placeables/shared/framework.lua^7:93)
[    976906] [b2944_GTAProce]             MainThrd/ ^3> placeItem^7 (^5@wp-placeables/client/placeables.lua^7:80)
[    976906] [b2944_GTAProce]             MainThrd/ ^3> fn^7 (^5@wp-placeables/client/placeables.lua^7:176)

**Comment by BackSH00TER** [comment] 2023-12-30 18:55
@Sina30 that error seems to indicate that the CreateLog function does not exist. 
Did you pull latest wp-placeables as well? You should have a CreateLog function in the framework file: https://github.com/WaypointRP/wp-placeables/blob/f1168b0e70f76f39532d434d6f24bc79da750ecf/shared/framework.lua#L169C1-L169C1

**Comment by BackSH00TER** [comment] 2023-12-31 04:22
@Sina30  please share all the steps you have taken for setup, what settings you have for the different framework options, what the errors you see on client or server (if any). A repro video might also be helpful, its not clear to me exactly what the issue is that you are facing. Is it that you get the item, but when you use it it doesnt open the document image, you dont get the item after inserting url, something else?

**Comment by Sina30** [comment] 2023-12-31 08:11
We set everything up like below in the readme file, then we wanted to use an image from Discord

printer config
```
Config.Framework = 'esx' -- supports 'qb' or 'esx'
Config.Notify = 'esx' -- supports 'qb', 'esx', 'ox' (if using ox enable @ox_lib/init.lua in the manifest)
Config.Inventory = 'ox'     -- 'qb', 'esx', 'ox'
```
placeables config
```
Config.Framework = 'esx' -- supports 'qb' or 'esx'
Config.Notify = 'esx' -- supports 'qb', 'esx', 'ox' (if using ox enable @ox_lib/init.lua in the manifest)
Config.Target = 'ox'        -- 'qb', 'ox'
Config.Inventory = 'ox'     -- 'qb', 'esx', 'ox'
```
```
-- Uncomment this line if you are using wp-printer
local printerCustomTargetOptions = {
    {
        event = "wp-printer:client:UsePrinter",
        icon = "fas fa-print",
        label = "Drucker verwenden",
    },
}
```

```
-- Printers
    -- Uncomment this line if you are using wp-printer
        {
            item = "printer", 
            label = "Printer", 
            model = "prop_printer_01", 
            isFrozen = true, 
            customTargetOptions = printerCustomTargetOptions
        },
        {
            item = "printer2", 
            label = "Printer", 
            model = "prop_printer_02", 
            isFrozen = true, 
            customTargetOptions = printerCustomTargetOptions
        },
        {
            item = "printer3", 
            label = "Printer", 
            model = "v_res_printer", 
            isFrozen = true, 
            customTargetOptions = printerCustomTargetOptions
        },
        {
            item = "printer4", 
            label = "Printer", 
            model = "v_ret_gc_print", 
            isFrozen = true, 
            customTargetOptions = printerCustomTargetOptions
        },
        {
            item = "photocopier", 
            label = "Photocopier",
            model = "v_med_cor_photocopy", 
            isFrozen = true, 
            customTargetOptions = printerCustomTargetOptions
        },
```

**Comment by BackSH00TER** [comment] 2023-12-31 20:54
@Sina30 Please provide a video repro'ing your issue, its still not clear to me where you are encountering the issue.

**Comment by BackSH00TER** [comment] 2024-01-03 07:58
@Sina30  Your issue may have been related to https://github.com/WaypointRP/wp-printer/issues/1, which we pushed a fix for. There was a bug with the ESX implementation when you used the item. Pull latest code and see check if your issue is resolved please

**Comment by Sina30** [comment] 2024-01-03 14:18
I now have the new version on it, I have it in front of me, I want to take a DC photo, everything works, but when I press print, nothing happens, it doesn't give me the picture, regardless of whether it's jpg or png

**Comment by BackSH00TER** [comment] 2024-01-04 03:28
What do you mean by DC photo? Are you referring to a discord photo?
Try a different image URL and see if it works to rule out if discord photo is the cause of the issue. 

I've tested that with default qb, default qb + default ox, default esx + default ox, and everything is working from my end. It's hard for me to say what specifically is going wrong with your setup as it could be any number of things. 

I would recommend that you trace the code starting from the button click to print and add console/print logs everywhere, in the UI, client and server code. Figure out where it gets to and if its getting stuck somewhere. At this point this is really the only viable way to debug your issue and should give a good picture of where the problem is.

**Comment by BackSH00TER** [comment] 2024-02-03 04:18
Closing as stale issue, no further information was provided.

**Closed as completed by BackSH00TER** 2024-02-03 04:18 UTC
